language: go
sudo: required

matrix:
  include:
  - name: amd64
    os: linux
    env: ARCH=amd64
  - name: ppc64le
    os: linux-ppc64le
    env:
      - ARCH=ppc64le
      - DOCKERFILE=Dockerfile.ppc64le

go:
  - "1.10"

env:
  global:
  - PATH=$GOROOT/bin:$GOPATH/bin:$PATH

before_install:
  - sudo systemctl restart docker

script:
  - make lint
  - sudo -E env "PATH=$PATH" make test
  - make build
  - make image

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"

deploy:
  # Push image to Dockerhub on merge to master
  - provider: script
    skip_cleanup: true
    script: >
      bash -c '
      if [ "${ARCH}" == "amd64" ]; then
        docker push nfvpe/sriov-cni
      fi
      docker tag nfvpe/sriov-cni nfvpe/sriov-cni:$ARCH;
      docker push nfvpe/sriov-cni:$ARCH;
      echo foo'
    on:
      branch: master
  # Push image to Dockerhub on tag
  - provider: script
    skip_cleanup: true
    script: >
      bash -c '
      if [ "${ARCH}" == "amd64" ]; then
        docker tag nfvpe/sriov-cni nfvpe/sriov-cni:$TRAVIS_TAG;
        docker push nfvpe/sriov-cni:$TRAVIS_TAG
      fi
      docker tag nfvpe/sriov-cni nfvpe/sriov-cni:$TRAVIS_TAG-$ARCH;
      docker push nfvpe/sriov-cni:$TRAVIS_TAG-$ARCH;
      echo foo'
    on:
      tags: true
      all_branches: true
      condition: "$TRAVIS_TAG =~ ^v[0-9].*$"
